Repository falcosecurity/pdig, pull requests merged in 2020-05, with the labels that each got.

#9 update: add Lorenzo and Leonardo to owners
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#7 Fix filter levels
  pdig.cc
Labels: approved, dco-signoff: yes, lgtm, size/M

#6 Fix for filters with more than 255 syscalls
  pdig.cc
Labels: approved, dco-signoff: yes, lgtm, size/M

#10 Inject getsockname/getpeername syscalls instead of parsing /proc
  pdig.cc
  pdig.h
  pdig_compat.c
Labels: approved, dco-signoff: yes, lgtm, size/XL
